//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat7
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние.
    /// </summary>
    // *** Start programmer edit section *** (Состояние CustomAttributes)

    // *** End programmer edit section *** (Состояние CustomAttributes)
    public enum Состояние
    {
        
        // *** Start programmer edit section *** (Состояние.1 CustomAttributes)

        // *** End programmer edit section *** (Состояние.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (Состояние.2 CustomAttributes)

        // *** End programmer edit section *** (Состояние.2 CustomAttributes)
        2,
        
        // *** Start programmer edit section *** (Состояние.3 CustomAttributes)

        // *** End programmer edit section *** (Состояние.3 CustomAttributes)
        3,
        
        // *** Start programmer edit section *** (Состояние.4 CustomAttributes)

        // *** End programmer edit section *** (Состояние.4 CustomAttributes)
        4,
        
        // *** Start programmer edit section *** (Состояние.5 CustomAttributes)

        // *** End programmer edit section *** (Состояние.5 CustomAttributes)
        5,
        
        // *** Start programmer edit section *** (Состояние.6 CustomAttributes)

        // *** End programmer edit section *** (Состояние.6 CustomAttributes)
        6,
        
        // *** Start programmer edit section *** (Состояние.7 CustomAttributes)

        // *** End programmer edit section *** (Состояние.7 CustomAttributes)
        7,
    }
}
