//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat7
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.1 CustomAttributes)

        // *** End programmer edit section *** (Статус.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (Статус.2 CustomAttributes)

        // *** End programmer edit section *** (Статус.2 CustomAttributes)
        2,
        
        // *** Start programmer edit section *** (Статус.3 CustomAttributes)

        // *** End programmer edit section *** (Статус.3 CustomAttributes)
        3,
    }
}
